// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_3X9S3ykypxxmPONP8FAvoru9YNk_REA',
    appId: '1:168095101720:web:fa1b93c5ddd65694cfe46d',
    messagingSenderId: '168095101720',
    projectId: 'book-donation-dev',
    authDomain: 'book-donation-dev.firebaseapp.com',
    storageBucket: 'book-donation-dev.firebasestorage.app',
    measurementId: 'G-CFHTJWFWE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbTDnrE_tuai99Ts9BcWU1-8h_3LWpMeI',
    appId: '1:168095101720:android:4a472ac694bd946dcfe46d',
    messagingSenderId: '168095101720',
    projectId: 'book-donation-dev',
    storageBucket: 'book-donation-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9vtwv8phJvTi3YNsaphZuCndrY_JTbsc',
    appId: '1:168095101720:ios:deb2626e41319e7acfe46d',
    messagingSenderId: '168095101720',
    projectId: 'book-donation-dev',
    storageBucket: 'book-donation-dev.firebasestorage.app',
    androidClientId: '168095101720-djpt5js9a0jf5jl1faish8of8io1npdg.apps.googleusercontent.com',
    iosClientId: '168095101720-1uol84g93edjqcvqp9b4eldcv9fdnpfe.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookdonationapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9vtwv8phJvTi3YNsaphZuCndrY_JTbsc',
    appId: '1:168095101720:ios:deb2626e41319e7acfe46d',
    messagingSenderId: '168095101720',
    projectId: 'book-donation-dev',
    storageBucket: 'book-donation-dev.firebasestorage.app',
    androidClientId: '168095101720-djpt5js9a0jf5jl1faish8of8io1npdg.apps.googleusercontent.com',
    iosClientId: '168095101720-1uol84g93edjqcvqp9b4eldcv9fdnpfe.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookdonationapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_3X9S3ykypxxmPONP8FAvoru9YNk_REA',
    appId: '1:168095101720:web:475c5a036211ca42cfe46d',
    messagingSenderId: '168095101720',
    projectId: 'book-donation-dev',
    authDomain: 'book-donation-dev.firebaseapp.com',
    storageBucket: 'book-donation-dev.firebasestorage.app',
    measurementId: 'G-14PN4CRXYW',
  );

}